name: Desplegar Documentación a Confluence v2

on:
  push:
    branches:
      - master

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: Publicar Markdown en Confluence
        uses: cupcakearmy/confluence-markdown-sync@v1
        with:
          from: './docs/Documentation.md'
          to: '1966084'
          cloud: cemssa
          user: mginovart@cemssa.cat
          token: ${{ secrets.CONFLUENCE_API_TOKEN }}
