name: Desplegar Documentación a Confluence v2

on:
  push:
    branches:
      - master

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: Publicar Markdown en Confluence
        uses: axro-gmbh/markdown-to-confluence-sync@v1.4
        with:
          input_directory: ./docs
          cloud: "cemssa"
          space_key: "cemssa"
          parent_page_id: "1966084"
          user: ${{ secrets.CONFLUENCE_EMAIL }}
          token: ${{ secrets.CONFLUENCE_API_TOKEN }}
